name: 🔄 100% Auto Token Generator

on:
  schedule:
    - cron: "*/30 * * * *" # প্রতি ৩০ মিনিট পর পর চেক করবে
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Tools
        run: pip install requests
      - name: Execute Script
        run: python auto_generator.py
      - name: Save to Repo
        run: |
          git config --global user.name "Auto-Bot"
          git config --global user.email "bot@github.com"
          git add playlist.m3u8
          git commit -m "Updated Token at $(date)" || exit 0
          git push
