name: Update BDIX Token
on:
  schedule:
    - cron: '*/10 * * * *' # প্রতি ১০ মিনিট পর পর চলবে
  workflow_dispatch: # ম্যানুয়ালি চালানোর জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Token Scraper
        run: python auto_generator.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u8
          git commit -m "Updated Token" || exit 0
          git push
